Contributing guidelines
iobis/pyobis pull request #26
Opened 2022-07-12 15:09 UTC by ayushanand18

## Overview
This PR aims to add Contributor Guidelines on CONTRIBUTING.md to the pyobis project.
+ It aims to resolve #19 

## Notes for Reviewers
Please review the Contributor Guidelines and highlight changes if I need to add some more points here.

## Next Steps
I am now working on creating a PR for the `usage_guide.ipynb` file post this review.

2022-07-14 17:15 UTC, 7yl4r requested changes

2022-07-14 17:15 UTC, 7yl4r commented on CONTRIBUTING.md
> +5. Make sure your code lints.
we can drop 4 and 5 here. We'll handle that using GH actions after the pull request is submitted.

2022-07-14 17:40 UTC, ayushanand18 commented on CONTRIBUTING.md
> +5. Make sure your code lints.
Thanks @7yl4r for the review! I'll modify the guidelines accordingly.

2022-07-15 05:53 UTC, ayushanand18 commented
I have updated the contributing guide as per the changes suggested. I have also added some sections:
+ `why contribute to the open source?`
+ `pyobis, and its aim`
+ `additional suggestions`
+ `further reading`

2022-07-15 16:09 UTC, 7yl4r approved these changes

2022-07-15 16:09 UTC, merged